name: deploy

env: 
  VIPSVER: 8.10.5

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with: 
          node-version: '12'
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
        run: |
          npx @getmeli/cli upload
          exit 1

      - name: download vips
        run: |
          wget -O ./vips.tar.gz https://github.com/libvips/libvips/releases/download/v$VIPSVER/vips-$VIPSVER.tar.gz

      - name: cached gems
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: cached vips
        id: vips-cache
        uses: actions/cache@v2
        with:
          path: vips
          key: ${{ runner.os }}-vips-${{ hashFiles('vips.tar.gz') }}

      - name: build vips dependency
        if: steps.vips-cache.outputs.cache-hit != true
        run: |
          tar -xvzf ./vips.tar.gz 
          mv vips-$VIPSVER vips
          cd vips
          ./configure 
          make -j4

      - name: install vips
        run: | 
          cd vips
          sudo make install

      - name: install dependencies
        run: | 
          gem install bundler jekyll 
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: build site
        run: bundle exec jekyll build

      - name: deploy site
        env: 
          MELI_TOKEN: ${{ secrets.MELI_TOKEN }}
          MELI_SITE: 6c20bd38-7b21-4092-b830-70d8511d3b58
        run: |
          npx @getmeli/cli upload --url https://web.lord.farm --site $MELI_SITE --token $MELI_TOKEN --release $GITHUB_SHA  ./_site


